apiVersion: v1
kind: Secret
metadata:
  name: motortech-secrets
  namespace: motortech
type: Opaque
data:
  APP_KEY: CHANGE_ME_BASE64
  JWT_SECRET: CHANGE_ME_BASE64
  WEBHOOK_TOKEN: CHANGE_ME_BASE64
  DB_PASSWORD: CHANGE_ME_BASE64
  NEW_RELIC_LICENSE_KEY: CHANGE_ME_BASE64
